[package]
name = "rust-openai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.7.0"
clap = { version = "4.1.6", features = ["derive"] }
